from pathlib import Path
import html
root=Path(__file__).resolve().parents[1]
names={'wanees':'Wanees · ونيس','amer':'Amer · عامر','maryam':'Maryam · مريم','clinician-male':'Male clinician','clinician-female':'Female clinician','stethoscope':'Stethoscope','thermometer':'Thermometer','xray':'X-ray equipment',**{'rooms/'+n:n.title()+' setting' for n in ['entrance','reception','assessment','xray','exit','coast']}}
cards=[]
for name,title in names.items():
 stem=name.replace('/','-');file=root/'apps/web/public/models'/f'{name}.glb';size=file.stat().st_size/1e6
 cards.append(f'<article><img loading="lazy" src="apps/web/public/posters/{stem}.png" alt="{html.escape(title)}"><div><h2>{html.escape(title)}</h2><p>{size:.2f} MB interactive model'+(' · 8 motions + blinks' if name in list(names)[:5] else '')+f'</p><a href="assets/blender/{stem}.blend">Open Blender source ↗</a><a class="secondary" href="apps/web/public/models/{name}.glb">GLB export</a></div></article>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wanees · A softer world</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f3eb;color:#294c46;font:16px/1.6 system-ui}header,main,footer{max-width:1200px;margin:auto;padding:40px}header{padding-top:64px}.eyebrow{text-transform:uppercase;letter-spacing:.16em;font-size:12px}h1{font:clamp(40px,6vw,76px)/1.05 Georgia;margin:18px 0}h2{font:26px Georgia;margin:0 0 12px}p{max-width:740px;color:#5a6e64}.hero{width:100%;border-radius:28px;margin-top:24px}.motion{display:grid;grid-template-columns:1.4fr 1fr;gap:30px;align-items:center;margin:28px 0 50px}video{width:100%;border-radius:20px;background:#ddd7c9}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:24px}article{overflow:hidden;border-radius:20px;background:#fff;border:1px solid #e2e4d9}article img{width:100%;aspect-ratio:1;object-fit:cover;display:block}article div{padding:24px}article p{font-size:13px}a{display:inline-block;color:#285e55;text-underline-offset:5px;margin-right:16px}.secondary{font-size:13px}footer{font-size:14px;border-top:1px solid #ddd}@media(max-width:650px){header,main,footer{padding:24px}.motion{grid-template-columns:1fr}}</style><header><div class="eyebrow">Wanees · ونيس / Blender collection</div><h1>A softer world.<br>A familiar friend.</h1><p>Wanees the sheep, Amer and Maryam—rebuilt as animated 3D companions with softer faces, warm materials and Omani welcome clothing.</p><img class="hero" src="Cast-preview.png" alt="Maryam, Wanees and Amer together"><div class="motion"><video controls loop playsinline preload="metadata" poster="Cast-preview.png"><source src="Cast-motion.mp4" type="video/mp4"></video><div><h2>A little hello.</h2><p>This is the actual Blender animation. The app includes waving, listening, pointing, demonstrating, breathing, encouragement, goodbye and idle movement.</p><a href="assets/blender/Cast.blend">Open the cast in Blender ↗</a><p>Open <strong>Start Wanees.command</strong> in this folder to use the complete app. In Blender, press Space to preview a character’s idle motion; use the NLA tracks to select another action.</p></div></div></header><main><div class="grid">'''+''.join(cards)+'''</div></main><footer>Editable scenes and web exports are included. The GLBs require a meshopt-compatible viewer; use the .blend files for editing in Blender. These are stylized reference-led adaptations, not finished television production assets. <a href="docs/3D-ASSET-HANDOFF.md">Source and rebuild notes</a> · <a href="docs/CHARACTER-REVISION.md">Softening changes</a></footer></html>'''
(root/'Models.html').write_text(page)
print('Models.html updated with actual asset sizes')
